# Generated by Django 3.2.12 on 2022-08-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام و نام خانوادگی')),
                ('first_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام')),
                ('username', models.CharField(blank=True, max_length=40, null=True, verbose_name='نام کاربری')),
                ('last_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
                ('collage', models.CharField(blank=True, max_length=20, null=True, verbose_name='دانشکده')),
                ('major', models.CharField(blank=True, max_length=20, null=True, verbose_name='رشته تحصیلی')),
                ('province', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('entering_year', models.CharField(blank=True, max_length=8, null=True, verbose_name='سال ورود')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='تلفن همراه')),
                ('student_code', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='آیا مدیر است؟')),
                ('is_active', models.BooleanField(default=True, verbose_name='آیا فعال است؟')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز')),
                ('date_joined', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'حساب کاربری',
                'verbose_name_plural': 'حساب های کاربری',
            },
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields_of_activity', models.TextField(verbose_name='زمینه های فعالیت')),
                ('interests', models.TextField(verbose_name='علاقه مندی ها')),
                ('descriptions', models.TextField(verbose_name='توضیحات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر راهنما',
                'verbose_name_plural': 'کاربران راهنما',
            },
        ),
    ]
