# Generated by Django 3.2 on 2022-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220806_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='نام کاربری'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='آیا فعال است؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='آیا مدیر است؟'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='امتیاز'),
        ),
    ]
