# Generated by Django 3.2 on 2022-08-06 06:25

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220806_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ عضویت'),
        ),
    ]
