# Generated by Django 3.2 on 2022-08-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_code',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
