# Generated by Django 3.2 on 2022-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='student_code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
