# Generated by Django 3.2 on 2022-08-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='کاربر'),
        ),
    ]
