# Generated by Django 3.2 on 2022-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='entering_year',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='سال ورود'),
        ),
    ]
