# Generated by Django 3.2 on 2022-08-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20220806_1253'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی')),
                ('sub_category', models.CharField(max_length=20, verbose_name='زیر دسته بندی')),
                ('is_sub', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='CreateNewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('data_create', models.DateField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('answered', 'has been answered'), ('waiting', "Waiting for members' response"), ('following', 'Following up from the relevant official'), ('closed', 'Closed'), ('open', 'Open')], max_length=20, verbose_name='وضعیت پاسخ گویی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adviser.category', verbose_name='دسته بندی سوال')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adviser.tag', verbose_name='تگ سوال')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.responder', verbose_name='فرد پاسخگو')),
            ],
        ),
    ]
