# Generated by Django 3.2.12 on 2022-08-26 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی')),
                ('is_sub', models.BooleanField(default=False)),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='adviser.category', verbose_name='زیر دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'برچسب سوال',
                'verbose_name_plural': 'برچسب سوالات',
            },
        ),
        migrations.CreateModel(
            name='CreateNewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='سوال')),
                ('data_create', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ ایجاد سوال')),
                ('is_public', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('answered', 'has been answered'), ('waiting', "Waiting for members' response"), ('following', 'Following up from the relevant official'), ('closed', 'Closed'), ('open', 'Open')], max_length=20, verbose_name='وضعیت پاسخ گویی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adviser.category', verbose_name='دسته بندی سوال')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='adviser.tag', verbose_name='تگ سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': ' سوالات',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('date_time', django_jalali.db.models.jDateField(auto_now=True, verbose_name='تاریخ پاسخ به سوال')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.responder', verbose_name='فرد پاسخگو')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='adviser.createnewquestion', verbose_name='پاسخ سوال')),
            ],
            options={
                'verbose_name': 'پاسخ سوال',
                'verbose_name_plural': 'پاسخ سوالات',
            },
        ),
    ]
