# Generated by Django 3.2 on 2022-08-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ سوال', 'verbose_name_plural': 'پاسخ سوالات'},
        ),
        migrations.AlterModelOptions(
            name='createnewquestion',
            options={'verbose_name': 'ایجاد سوال جدید', 'verbose_name_plural': 'ایجاد سوالات جدید'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب سوال', 'verbose_name_plural': 'برچسب سوالات'},
        ),
    ]
