# Generated by Django 3.2 on 2022-08-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0002_auto_20220808_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='adviser.createnewquestion', verbose_name='پاسخ سوال'),
            preserve_default=False,
        ),
    ]
