# Generated by Django 3.2 on 2022-08-12 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0004_alter_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scategory', to='adviser.category', verbose_name='زیر دسته بندی'),
        ),
        migrations.AlterField(
            model_name='createnewquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='adviser.category', verbose_name='دسته بندی سوال'),
        ),
        migrations.AlterField(
            model_name='createnewquestion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='adviser.tag', verbose_name='تگ سوال'),
        ),
    ]
