# Generated by Django 3.2 on 2022-08-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0006_auto_20220821_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createnewquestion',
            options={'verbose_name': 'سوال', 'verbose_name_plural': ' سوالات'},
        ),
    ]
