# Generated by Django 3.2 on 2022-08-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviser', '0007_alter_createnewquestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnewquestion',
            name='author',
            field=models.CharField(max_length=12, verbose_name='کاربر'),
        ),
    ]
